[mosip_auth]
timestamp_format = "%Y-%m-%dT%H:%M:%S"
ida_auth_version = "1.0"
ida_auth_request_demo_id = "mosip.identity.auth"
ida_auth_request_kyc_id = "mosip.identity.kyc"
ida_auth_request_otp_id = "mosip.identity.otp"
ida_auth_env = "Staging"
authorization_header_constant = "Authorization"
partner_misp_lk = "9FChkkfixwsSFSvBaA7oCOkfNnBUj2XIZObAtyOGHsIAyG0JOG"
partner_apikey = "403286"
partner_id = "cs-198-2"

[mosip_auth_server]
ida_auth_domain_uri = "https://api-internal.collab.mosip.net"
ida_auth_url = "https://api.collab.mosip.net/idauthentication/v1"


[crypto_encrypt]
symmetric_key_size = 256
symmetric_nonce_size = 128
symmetric_gcm_tag_size = 128
# certificate from the path below is used to encrypt the Auth Request.
encrypt_cert_path = "/home/chris/cs198/NDSL-HMI/middleware/registration_authority/verification/idverification/mosip/ida_partner.pem"
# used to decrypt the received response
decrypt_p12_file_path = "/home/chris/cs198/NDSL-HMI/middleware/registration_authority/verification/idverification/mosip/cs-198-2-keystore-signed.p12"
decrypt_p12_file_password = "cs198-2-piidtl"

[crypto_signature]
algorithm = "RS256"
sign_p12_file_path =  "/home/chris/cs198/NDSL-HMI/middleware/registration_authority/verification/idverification/mosip/cs-198-2-keystore-signed.p12"
sign_p12_file_password = "cs198-2-piidtl"

[logging]
log_file_path = "authenticator.log"
log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
# loglevel can be one of "DEBUG" | "INFO" | "WARNING" | "ERROR" | "CRITICAL"
loglevel = "INFO" 
